// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// remove_node_cpp
DataFrame remove_node_cpp(IntegerVector from, IntegerVector to, NumericVector weight, int node, double path_threshold);
RcppExport SEXP _RcppLDGM_remove_node_cpp(SEXP fromSEXP, SEXP toSEXP, SEXP weightSEXP, SEXP nodeSEXP, SEXP path_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< double >::type path_threshold(path_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(remove_node_cpp(from, to, weight, node, path_threshold));
    return rcpp_result_gen;
END_RCPP
}
// reduce_graph_cpp
DataFrame reduce_graph_cpp(IntegerVector from, IntegerVector to, NumericVector weight, IntegerVector brick_id, IntegerVector mutation_id, double path_threshold);
RcppExport SEXP _RcppLDGM_reduce_graph_cpp(SEXP fromSEXP, SEXP toSEXP, SEXP weightSEXP, SEXP brick_idSEXP, SEXP mutation_idSEXP, SEXP path_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type brick_id(brick_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mutation_id(mutation_idSEXP);
    Rcpp::traits::input_parameter< double >::type path_threshold(path_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(reduce_graph_cpp(from, to, weight, brick_id, mutation_id, path_threshold));
    return rcpp_result_gen;
END_RCPP
}
// openmp_info_cpp
Rcpp::List openmp_info_cpp();
RcppExport SEXP _RcppLDGM_openmp_info_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(openmp_info_cpp());
    return rcpp_result_gen;
END_RCPP
}
// set_openmp_threads_cpp
int set_openmp_threads_cpp(int n_threads);
RcppExport SEXP _RcppLDGM_set_openmp_threads_cpp(SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(set_openmp_threads_cpp(n_threads));
    return rcpp_result_gen;
END_RCPP
}
// sparse_matmul_cpp
Rcpp::NumericMatrix sparse_matmul_cpp(SEXP precision, Rcpp::NumericMatrix x);
RcppExport SEXP _RcppLDGM_sparse_matmul_cpp(SEXP precisionSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_matmul_cpp(precision, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppLDGM_remove_node_cpp", (DL_FUNC) &_RcppLDGM_remove_node_cpp, 5},
    {"_RcppLDGM_reduce_graph_cpp", (DL_FUNC) &_RcppLDGM_reduce_graph_cpp, 6},
    {"_RcppLDGM_openmp_info_cpp", (DL_FUNC) &_RcppLDGM_openmp_info_cpp, 0},
    {"_RcppLDGM_set_openmp_threads_cpp", (DL_FUNC) &_RcppLDGM_set_openmp_threads_cpp, 1},
    {"_RcppLDGM_sparse_matmul_cpp", (DL_FUNC) &_RcppLDGM_sparse_matmul_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppLDGM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
