# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RC_brick_edges_from_tables <- function(initial_left, initial_right, initial_parent, initial_child, transition_id, transition_left, out_transition, out_child, in_transition, in_left, in_right, in_parent, in_child, state_transition, state_node, state_prev_parent, state_curr_parent, state_time, state_num_samples, num_samples, recombination_freq_threshold) {
    .Call(`_RcppLDGM_brick_edges_from_tables_cpp`, initial_left, initial_right, initial_parent, initial_child, transition_id, transition_left, out_transition, out_child, in_transition, in_left, in_right, in_parent, in_child, state_transition, state_node, state_prev_parent, state_curr_parent, state_time, state_num_samples, num_samples, recombination_freq_threshold)
}

RC_brick_graph_inputs_from_edges <- function(edge_id, left, right, parent, child, sample_nodes) {
    .Call(`_RcppLDGM_brick_graph_inputs_from_edges_cpp`, edge_id, left, right, parent, child, sample_nodes)
}

RC_mutations_to_bricks <- function(edge_id, edge_left, edge_right, edge_child, mutation_id, mutation_position, mutation_node) {
    .Call(`_RcppLDGM_mutations_to_bricks_cpp`, edge_id, edge_left, edge_right, edge_child, mutation_id, mutation_position, mutation_node)
}

RC_make_snplist_index <- function(mutation_id, mutation_groups) {
    .Call(`_RcppLDGM_make_snplist_index_cpp`, mutation_id, mutation_groups)
}

RC_brick_haplo_graph <- function(brick_id, brick_child, frequency, labeled_brick, event_focal_brick, event_parent_brick, event_child_bricks, event_sibling_bricks, event_has_parent, has_edge_weight_threshold, edge_weight_threshold, make_sibs) {
    .Call(`_RcppLDGM_brick_haplo_graph_cpp`, brick_id, brick_child, frequency, labeled_brick, event_focal_brick, event_parent_brick, event_child_bricks, event_sibling_bricks, event_has_parent, has_edge_weight_threshold, edge_weight_threshold, make_sibs)
}

RC_finalize_ldgm <- function(h1_from, h1_to, h1_weight, h2_from, h2_to, h2_weight, mutation_id, path_threshold) {
    .Call(`_RcppLDGM_finalize_ldgm_cpp`, h1_from, h1_to, h1_weight, h2_from, h2_to, h2_weight, mutation_id, path_threshold)
}

RC_remove_node <- function(from, to, weight, node, path_threshold) {
    .Call(`_RcppLDGM_remove_node_cpp`, from, to, weight, node, path_threshold)
}

RC_reduce_graph <- function(from, to, weight, brick_id, mutation_id, path_threshold) {
    .Call(`_RcppLDGM_reduce_graph_cpp`, from, to, weight, brick_id, mutation_id, path_threshold)
}

RC_hdf5_filter_info <- function() {
    .Call(`_RcppLDGM_hdf5_filter_info_cpp`)
}

RC_write_graphld_score_hdf5 <- function(filename, variant_data, gradient, hessian, trait_name, jackknife_blocks, overwrite, source, compression, chunk_size, parameters, jackknife_parameters) {
    .Call(`_RcppLDGM_write_graphld_score_hdf5_cpp`, filename, variant_data, gradient, hessian, trait_name, jackknife_blocks, overwrite, source, compression, chunk_size, parameters, jackknife_parameters)
}

RC_read_graphld_score_hdf5 <- function(filename, trait_name) {
    .Call(`_RcppLDGM_read_graphld_score_hdf5_cpp`, filename, trait_name)
}

RC_openmp_info <- function() {
    .Call(`_RcppLDGM_openmp_info_cpp`)
}

RC_set_openmp_threads <- function(n_threads) {
    .Call(`_RcppLDGM_set_openmp_threads_cpp`, n_threads)
}

RC_sparse_matmul <- function(precision, x) {
    .Call(`_RcppLDGM_sparse_matmul_cpp`, precision, x)
}

RC_tskit_tree_tables_from_file <- function(path) {
    .Call(`_RcppLDGM_tskit_tree_tables_from_file_cpp`, path)
}

