# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RC_remove_node <- function(from, to, weight, node, path_threshold) {
    .Call(`_RcppLDGM_remove_node_cpp`, from, to, weight, node, path_threshold)
}

RC_reduce_graph <- function(from, to, weight, brick_id, mutation_id, path_threshold) {
    .Call(`_RcppLDGM_reduce_graph_cpp`, from, to, weight, brick_id, mutation_id, path_threshold)
}

RC_openmp_info <- function() {
    .Call(`_RcppLDGM_openmp_info_cpp`)
}

RC_set_openmp_threads <- function(n_threads) {
    .Call(`_RcppLDGM_set_openmp_threads_cpp`, n_threads)
}

RC_sparse_matmul <- function(precision, x) {
    .Call(`_RcppLDGM_sparse_matmul_cpp`, precision, x)
}
